### ISSUE TITLE
How Can I send messages without any backend server support

### ISSUE THREAD

**Issue by kmuddapu** [twilio/ip-demo-ios#23]
How Can I send 1-1 messages without any backend server support?

**Comment by philnash** [comment]
With Twilio Programmable Chat you always need a backend server in order to produce access tokens for your users to give them access to the API.

You no longer have to run your own server to provide these tokens though. We recently launched [Twilio Function](http://twilio.com/functions) which allow you to write and host Node.js applications on Twilio as a serverless platform. Check out the [introductory blog post on Functions](https://www.twilio.com/blog/2017/05/introducing-twilio-functions.html) to see how they can work for you.
