### ISSUE TITLE
channel.uniqueName nil in the channelAdded callback

### ISSUE THREAD

**Issue by stefanluptak** [twilio/ip-demo-ios#29]
Hi,

when examining the `channel.uniqueName` inside the `func chatClient(_ client: TwilioChatClient, channel: TCHChannel, messageAdded message: TCHMessage) { ... }` delegated method of the `TwilioChatClientDelegate` protocol, `uniqueName` property of the `channel` is **nil** even though it was specified when called `channelsList.createChannel(options: [TCHChannelOptionUniqueName: "SomeChannelUniqueName", TCHChannelOptionType: TCHChannelType.private], completion: completion)`.

In other delegated methods (messageAdded, etc., the channel uniqueName is specified).

Is this a bug or a feature?

Thank you for your assistance.

**Comment by rbeiter** [comment]
Hi @EskiMag ,

Depending on the timing, the channel can sometimes be not yet fully synchronized locally when the channel added events are fired, and synchronization may still be in process.

This can be checked using the `.synchronizationStatus` property and comparing against `TCHChannelSynchronizationStatusAll`.  You can also wait for the `chatClient:channel:synchronizationStatusUpdated:` delegate method with that same `status` for confirmation when synchronization is complete for the channel.

Above, you mention `messageAdded` does not see `uniqueName` but mention it does later in your inquiry.  Did you maybe mean `channelAdded` in the initial part of the question?  If so, I believe what I describe above may be what you are seeing?

Thank you,
Randy

**Comment by stefanluptak** [comment]
Oh, sorry. I meant that in `channelAdded` the `uniqueName` is `nil` but in `messageAdded` it has correct value.

**Comment by stefanluptak** [comment]
And yes, what you're describing makes sense. I was just not completely sure whether it's a bug or a feature, because `uniqueName` seems to be a basic info about the channel to me so I assumed it'll be available immediately.

**Comment by rbeiter** [comment]
Got it – we definitely see the utility in having the properties available at the time of the channel added being called and you are not the first person to mention this would be the desired behavior.  I will make note of your +1 to this feature request in our system!

**Comment by stefanluptak** [comment]
Thank you for upvoting that. Do you have an idea when or if this could be part of the `TwilioChatClient` CocoaPod?

**Comment by rbeiter** [comment]
Hi @EskiMag ,

Unfortunately, we don't have a time frame to share for this item at this time.

Thank you,
Randy

**Comment by marcosiino** [comment]
I had the same problem and i saw this issue is still opened. In my case when i receive the channel added call back, both the TCHChannel instance passed to the callback and the new channel returned in the client.channelList() array lacks some properties (like channel attributes, unique name, etc.... which are nil). Also if check the client syncronization state it is completed: i think this should be flagged as bug instead of enhancement, could you verify please ?

Btw i solved for now in this way: when i receive the channel added / updated / deleted callback, i reconnect the client and wait for synchronization status to be completed, then i fetch the channels again...at that point i get the channels with all the properties set correctly.

**Comment by Gray-Wind** [comment]
This should be solved in last releases. If you still face such an issue, please open new ticket.
