### ISSUE TITLE
Typing indicator does not seem to work

### ISSUE THREAD

**Issue by MilanNosal** [twilio/ip-demo-ios#42]
Working on a Swift chat application.
On one device, I join a channel with unique name `"private:chat"`, and then I call `channel.typing()` on the channel.
On another device, I again create a client with a delegate set to self:

    TwilioChatClient.chatClient(withToken: token, properties: nil, delegate: self) {
                    (result, chatClient) in
                    self.client = chatClient
                }

And then I implemented `typingStartedOn` delegate method to listen to typing on the channel.

    func chatClient(_ client: TwilioChatClient, typingStartedOn channel: TCHChannel, member: TCHMember) {
        print(">>>>>>>>>>>>> typing on \(channel.uniqueName) by \(member.identity)")
    }

However, the delegate method does not get called, even though I confirmed that the `channel.typing()` gets called by the other account on the other device.

Any idea what might be the reason?

**Comment by rbeiter** [comment]
Hi @MilanNosal - I'm sorry you are experiencing issues with the typing indicator feature.

I have a couple of questions for you to get started.  For the second client device, is the identity different or the same as the first device?  If it is the same, we do not send typing indications for the local user, so that may be one reason you are not seeing events.  Another question is assuming the identities are different, is the user for the second client joined to the channel?  Only channel members will receive typing indicator events.

If you are still encountering issues, may I ask you to set the logging level to debug (as shown [here](https://www.twilio.com/docs/chat/error-handling-and-diagnostics#logging)) and send the log to Twilio support via 
https://www.twilio.com/help/contact and reference this github issue?  We'll review the log and help get this resolved.

**Comment by MilanNosal** [comment]
Hi @rbeiter - thanks for the answer! In the end, the client was correctly implemented. I double checked the things you pointed out - I was setting the correct identity and whether the channel was joined. However, the problem was with our access token server, which ignored the identity and used a hardcoded value - so in the end, it was really the same chat member. Fixing the access token server fixed the problem. Thanks for the help, if you would not mention that you do not send typing indications for the local user, I would never investigate this part!

**Comment by AresVampire** [comment]
I am actually getting this problem. I checked token and it differs with identity and deviceId.
```
extension SwiftTwilio: TwilioChatClientDelegate {
    // TwilioChatClientDelegate
    
    @objc func chatClient(_ client: TwilioChatClient, synchronizationStatusUpdated status: TCHClientSynchronizationStatus) {
        if (status == TCHClientSynchronizationStatus.completed) {
        }
    }
    
    @objc func chatClient(_ client: TwilioChatClient, channel: TCHChannel, messageAdded message: TCHMessage) {
    }
    
    @objc func chatClient(_ client: TwilioChatClient, channel: TCHChannel, synchronizationStatusUpdated status: TCHChannelSynchronizationStatus) {
    }
    
    @objc func chatClient(_ client: TwilioChatClient, channelAdded channel: TCHChannel) {
    }
    
    @objc func chatClient(_ client: TwilioChatClient, channel: TCHChannel, updated: TCHChannelUpdate) {
    }
    
    @objc func chatClient(_ client: TwilioChatClient, typingStartedOn channel: TCHChannel, member: TCHMember) {
    }
    
    @objc func chatClient(_ client: TwilioChatClient, typingEndedOn channel: TCHChannel, member: TCHMember) {
    }
}
```

**Comment by AresVampire** [comment]
messageAdded, synchronizationStatusUpdated all works, but typingStartedOn doesn't work.

**Comment by evgenyshenets** [comment]
on another side(web sandbox or sth else) you have to call chatClientChannel.current?.typing() in onChange method, where chatClientChannel is conversation ref(type Conversation)

It will send action to twilio and listeners will start work.
